<?php

namespace Database\Seeders;

use App\Models\CurrencyMaster;
use Illuminate\Database\Seeder;

class CurrencyMasterSeeder extends Seeder
{
    /**
     * ISO 4217 world currency reference, covering every currency_code
     * present in country_masters — code => [name, symbol, decimal_digits].
     */
    public function run(): void
    {
        $currencies = [
            'AED' => ['UAE Dirham', 'د.إ', 2],
            'AFN' => ['Afghan Afghani', '؋', 2],
            'ALL' => ['Albanian Lek', 'L', 2],
            'AMD' => ['Armenian Dram', '֏', 2],
            'AOA' => ['Angolan Kwanza', 'Kz', 2],
            'ARS' => ['Argentine Peso', '$', 2],
            'AUD' => ['Australian Dollar', '$', 2],
            'AWG' => ['Aruban Florin', 'ƒ', 2],
            'AZN' => ['Azerbaijani Manat', '₼', 2],
            'BBD' => ['Barbadian Dollar', '$', 2],
            'BDT' => ['Bangladeshi Taka', '৳', 2],
            'BGN' => ['Bulgarian Lev', 'лв', 2],
            'BHD' => ['Bahraini Dinar', '.د.ب', 3],
            'BIF' => ['Burundian Franc', 'Fr', 0],
            'BMD' => ['Bermudian Dollar', '$', 2],
            'BND' => ['Brunei Dollar', '$', 2],
            'BRL' => ['Brazilian Real', 'R$', 2],
            'BTN' => ['Bhutanese Ngultrum', 'Nu.', 2],
            'BWP' => ['Botswana Pula', 'P', 2],
            'BYR' => ['Belarusian Ruble', 'Br', 0],
            'BZD' => ['Belize Dollar', '$', 2],
            'CAD' => ['Canadian Dollar', '$', 2],
            'CHF' => ['Swiss Franc', 'Fr', 2],
            'CLP' => ['Chilean Peso', '$', 0],
            'CNY' => ['Chinese Yuan', '¥', 2],
            'COP' => ['Colombian Peso', '$', 2],
            'CRC' => ['Costa Rican Colón', '₡', 2],
            'CUC' => ['Cuban Convertible Peso', '$', 2],
            'CVE' => ['Cape Verdean Escudo', '$', 2],
            'CZK' => ['Czech Koruna', 'Kč', 2],
            'DJF' => ['Djiboutian Franc', 'Fr', 0],
            'DKK' => ['Danish Krone', 'kr', 2],
            'DOP' => ['Dominican Peso', 'RD$', 2],
            'DZD' => ['Algerian Dinar', 'د.ج', 2],
            'EGP' => ['Egyptian Pound', '£', 2],
            'ERN' => ['Eritrean Nakfa', 'Nfk', 2],
            'ETB' => ['Ethiopian Birr', 'Br', 2],
            'EUR' => ['Euro', '€', 2],
            'FJD' => ['Fijian Dollar', '$', 2],
            'GBP' => ['British Pound', '£', 2],
            'GEL' => ['Georgian Lari', 'ლ', 2],
            'GHS' => ['Ghanaian Cedi', '₵', 2],
            'GIP' => ['Gibraltar Pound', '£', 2],
            'GNF' => ['Guinean Franc', 'Fr', 0],
            'GTQ' => ['Guatemalan Quetzal', 'Q', 2],
            'GYD' => ['Guyanese Dollar', '$', 2],
            'HKD' => ['Hong Kong Dollar', '$', 2],
            'HNL' => ['Honduran Lempira', 'L', 2],
            'HRK' => ['Croatian Kuna', 'kn', 2],
            'HTG' => ['Haitian Gourde', 'G', 2],
            'HUF' => ['Hungarian Forint', 'Ft', 2],
            'IDR' => ['Indonesian Rupiah', 'Rp', 2],
            'ILS' => ['Israeli New Shekel', '₪', 2],
            'INR' => ['Indian Rupee', '₹', 2],
            'IQD' => ['Iraqi Dinar', 'ع.د', 3],
            'ISK' => ['Icelandic Króna', 'kr', 0],
            'JMD' => ['Jamaican Dollar', '$', 2],
            'JOD' => ['Jordanian Dinar', 'د.ا', 3],
            'JPY' => ['Japanese Yen', '¥', 0],
            'KES' => ['Kenyan Shilling', 'Sh', 2],
            'KGS' => ['Kyrgystani Som', 'лв', 2],
            'KHR' => ['Cambodian Riel', '៛', 2],
            'KMF' => ['Comorian Franc', 'Fr', 0],
            'KWD' => ['Kuwaiti Dinar', 'د.ك', 3],
            'KYD' => ['Cayman Islands Dollar', '$', 2],
            'KZT' => ['Kazakhstani Tenge', '₸', 2],
            'LAK' => ['Laotian Kip', '₭', 2],
            'LBP' => ['Lebanese Pound', 'ل.ل', 2],
            'LKR' => ['Sri Lankan Rupee', 'Rs', 2],
            'LRD' => ['Liberian Dollar', '$', 2],
            'LSL' => ['Lesotho Loti', 'L', 2],
            'MAD' => ['Moroccan Dirham', 'د.م.', 2],
            'MDL' => ['Moldovan Leu', 'L', 2],
            'MGA' => ['Malagasy Ariary', 'Ar', 2],
            'MMK' => ['Myanmar Kyat', 'Ks', 2],
            'MNT' => ['Mongolian Tögrög', '₮', 2],
            'MRO' => ['Mauritanian Ouguiya', 'UM', 2],
            'MUR' => ['Mauritian Rupee', '₨', 2],
            'MVR' => ['Maldivian Rufiyaa', '.ރ', 2],
            'MWK' => ['Malawian Kwacha', 'MK', 2],
            'MXN' => ['Mexican Peso', '$', 2],
            'MYR' => ['Malaysian Ringgit', 'RM', 2],
            'MZN' => ['Mozambican Metical', 'MT', 2],
            'NAD' => ['Namibian Dollar', '$', 2],
            'NGN' => ['Nigerian Naira', '₦', 2],
            'NIO' => ['Nicaraguan Córdoba', 'C$', 2],
            'NOK' => ['Norwegian Krone', 'kr', 2],
            'NPR' => ['Nepalese Rupee', '₨', 2],
            'NZD' => ['New Zealand Dollar', '$', 2],
            'OMR' => ['Omani Rial', 'ر.ع.', 3],
            'PAB' => ['Panamanian Balboa', 'B/.', 2],
            'PEN' => ['Peruvian Sol', 'S/.', 2],
            'PGK' => ['Papua New Guinean Kina', 'K', 2],
            'PHP' => ['Philippine Peso', '₱', 2],
            'PKR' => ['Pakistani Rupee', '₨', 2],
            'PLN' => ['Polish Zloty', 'zł', 2],
            'PYG' => ['Paraguayan Guarani', '₲', 0],
            'QAR' => ['Qatari Rial', 'ر.ق', 2],
            'RON' => ['Romanian Leu', 'lei', 2],
            'RSD' => ['Serbian Dinar', 'дин.', 2],
            'RUB' => ['Russian Ruble', '₽', 2],
            'RWF' => ['Rwandan Franc', 'Fr', 0],
            'SAR' => ['Saudi Riyal', 'ر.س', 2],
            'SBD' => ['Solomon Islands Dollar', '$', 2],
            'SCR' => ['Seychellois Rupee', '₨', 2],
            'SDG' => ['Sudanese Pound', 'ج.س.', 2],
            'SEK' => ['Swedish Krona', 'kr', 2],
            'SLL' => ['Sierra Leonean Leone', 'Le', 2],
            'SOS' => ['Somali Shilling', 'Sh', 2],
            'SRD' => ['Surinamese Dollar', '$', 2],
            'SZL' => ['Swazi Lilangeni', 'L', 2],
            'THB' => ['Thai Baht', '฿', 2],
            'TJS' => ['Tajikistani Somoni', 'ЅМ', 2],
            'TMT' => ['Turkmenistani Manat', 'm', 2],
            'TND' => ['Tunisian Dinar', 'د.ت', 3],
            'TOP' => ['Tongan Paanga', 'T$', 2],
            'TRY' => ['Turkish Lira', '₺', 2],
            'TTD' => ['Trinidad and Tobago Dollar', '$', 2],
            'TWD' => ['New Taiwan Dollar', '$', 2],
            'UAH' => ['Ukrainian Hryvnia', '₴', 2],
            'UGX' => ['Ugandan Shilling', 'Sh', 0],
            'USD' => ['US Dollar', '$', 2],
            'UYU' => ['Uruguayan Peso', '$', 2],
            'UZS' => ['Uzbekistani Som', "so'm", 2],
            'VND' => ['Vietnamese Dong', '₫', 0],
            'VUV' => ['Vanuatu Vatu', 'Vt', 0],
            'WST' => ['Samoan Tala', 'T', 2],
            'XAF' => ['Central African CFA Franc', 'Fr', 0],
            'XCD' => ['East Caribbean Dollar', '$', 2],
            'XOF' => ['West African CFA Franc', 'Fr', 0],
            'XPF' => ['CFP Franc', 'Fr', 0],
            'YER' => ['Yemeni Rial', '﷼', 2],
            'ZAR' => ['South African Rand', 'R', 2],
            'ZMW' => ['Zambian Kwacha', 'ZK', 2],
        ];

        foreach ($currencies as $code => [$name, $symbol, $decimalDigits]) {
            CurrencyMaster::updateOrCreate(
                ['code' => $code],
                [
                    'name' => $name,
                    'name_plural' => $name.'s',
                    'symbol' => $symbol,
                    'symbol_native' => $symbol,
                    'decimal_digits' => $decimalDigits,
                    'rounding' => 0,
                ]
            );
        }
    }
}
